# org: mialesta
app: etl-la-porte-bleue
service: etl-la-porte-bleue

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  environment:
    MONGO_DB: ${env:MONGO_DB}
    POSTGRES_DB: ${env:POSTGRES_DB}

functions:
  main:
    handler: handler.main
    # TODO: how do you want to trigger this? every day at 13:00

plugins:
  - serverless-python-requirements
