org: mialesta
app: etl-la-porte-bleue
service: etl-la-porte-bleue

frameworkVersion: '3'

plugins:
  - serverless-python-requirements

provider:
  name: aws
  # TODO: python3.7 ?
  runtime: python3.9
  environment:
    MONGO_DB: ${env:MONGO_DB}
    POSTGRES_DB: ${env:POSTGRES_DB}
  # TODO: iam role?
  # iam:
  #   role:
  #     managedPolicies:
  #       - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

functions:
  main:
    handler: handler.main
    timeout: 360
    events:
      # Invoke Lambda function everyday at 1pm CET
      - schedule: cron(0 11 * * ? *)
