org: mialesta
app: la-porte-bleue
service: etl

frameworkVersion: '3'

plugins:
  - serverless-python-requirements

provider:
  name: aws
  # TODO: python3.7 ?
  runtime: python3.9
  environment:
    MONGO_DB: ${env:MONGO_DB}
    POSTGRES_DB: ${env:POSTGRES_DB}
  # TODO: iam role?
  # iam:
  #   role:
  #     managedPolicies:
  #       - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

functions:
  cronHandler:
    handler: handler.main
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0 13 * * *)
